Update terraform-enviromements-action.yml

diff --git a/.github/workflows/terraform-enviromements-action.yml b/.github/workflows/terraform-enviromements-action.yml
--- a/.github/workflows/terraform-enviromements-action.yml
+++ b/.github/workflows/terraform-enviromements-action.yml
@@ -56,7 +56,9 @@ jobs:
           
       - name: Format Terraform
         id: fmt
-        run: terraform fmt #-check
+        run: |
+          terraform fmt #-check
+          aws sts get-caller-identity
         continue-on-error: true
 
       - name: Initialize Terraform
@@ -65,6 +67,7 @@ jobs:
           AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
           AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCEKT_KEY_NAME }}
         run: |
+          aws sts get-caller-identity
           pwd
           ls
           cd terraform/environments/dev/
@@ -80,6 +83,7 @@ jobs:
         run: |
           pwd
           ls
+          aws sts get-caller-identity
           cd terraform/environments/dev/
           terraform plan
           terraform plan -out plan.out -no-color
@@ -90,14 +94,14 @@ jobs:
 #           cd terraform/environments/dev/
 #           terraform destroy -auto-approve
         
-      - name: Terraform Plan Status
-        id: if_plan_error
-        if: steps.plan.outcome =='failure'
-        run: exit 1
+#       - name: Terraform Plan Status
+#         id: if_plan_error
+#         if: steps.plan.outcome =='failure'
+#         run: exit 1
 
-      - name: Terrafrom Apply
-        id: apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push' || github.ref == 'refs/heads/dev' && github.event_name == 'push'
-        run: | 
-          cd terraform/environments/dev/
-          terraform apply plan.out  # -auto-approve -input=false 
+#       - name: Terrafrom Apply
+#         id: apply
+#         if: github.ref == 'refs/heads/main' && github.event_name == 'push' || github.ref == 'refs/heads/dev' && github.event_name == 'push'
+#         run: | 
+#           cd terraform/environments/dev/
+#           terraform apply plan.out  # -auto-approve -input=false 
