Editing for testing parameter store retrieval.

diff --git a/.github/workflows/terraform-enviromements-action.yml b/.github/workflows/terraform-enviromements-action.yml
--- a/.github/workflows/terraform-enviromements-action.yml
+++ b/.github/workflows/terraform-enviromements-action.yml
@@ -70,19 +70,19 @@ jobs:
         id: validate
         run: terraform validate -no-color
       
-      - name: Terrafrom plan
-        id: plan
-        run: |
-          pwd
-          ls
-          cd terraform/environments/dev/
-          terraform plan -no-color
+#       - name: Terrafrom plan
+#         id: plan
+#         run: |
+#           pwd
+#           ls
+#           cd terraform/environments/dev/
+#           terraform plan -no-color
 
-        continue-on-error: true
-      - name: Terraform Plan Status
-        if: steps.plan.outcome =='failure'
-        run: exit 1
+#         continue-on-error: true
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome =='failure'
+#         run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false 
+#       - name: Terraform Apply
+#         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#         run: terraform apply -auto-approve -input=false 
