Update terraform-enviromements-action.yml

diff --git a/.github/workflows/terraform-enviromements-action.yml b/.github/workflows/terraform-enviromements-action.yml
--- a/.github/workflows/terraform-enviromements-action.yml
+++ b/.github/workflows/terraform-enviromements-action.yml
@@ -76,15 +76,15 @@ jobs:
           cd terraform/environments/dev/
           terraform plan -out plan.out -no-color
 
-        continue-on-error: true
-      - name: Terraform Plan Status
-        id: if_plan_error
-        if: steps.plan.outcome =='failure'
-        run: exit 1
+#         continue-on-error: true
+#       - name: Terraform Plan Status
+#         id: if_plan_error
+#         if: steps.plan.outcome =='failure'
+#         run: exit 1
 
       - name: Terrafrom Apply
         id: apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        if: github.ref == 'refs/heads/main' && github.event_name == 'push' || github.ref == 'refs/heads/dev' && github.event_name == 'push'
         run: | 
           cd terraform/environments/dev/
           terraform apply plan.out -auto-approve -input=false 
